export const userConstants = {
  LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

  GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',

  EXCHANGE_TOKEN_REQUEST: 'EXCHANGE_TOKEN_REQUEST',
  EXCHANGE_TOKEN_SUCCESS: 'EXCHANGE_TOKEN_SUCCESS',
  EXCHANGE_TOKEN_FAILURE: 'EXCHANGE_TOKEN_FAILURE',

  GO_TO_LOGIN_URL_REQUEST: 'GO_TO_LOGIN_URL_REQUEST',
  GO_TO_LOGIN_URL_FAILURE: 'GO_TO_LOGIN_URL_FAILURE',
}